/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yshi.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class InnerRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5989862320374407439L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InnerRecord\",\"namespace\":\"com.yshi.avro\",\"fields\":[{\"name\":\"desc\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"value\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String desc;
  @Deprecated public java.lang.String value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InnerRecord() {}

  /**
   * All-args constructor.
   * @param desc The new value for desc
   * @param value The new value for value
   */
  public InnerRecord(java.lang.String desc, java.lang.String value) {
    this.desc = desc;
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return desc;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: desc = (java.lang.String)value$; break;
    case 1: value = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'desc' field.
   * @return The value of the 'desc' field.
   */
  public java.lang.String getDesc() {
    return desc;
  }

  /**
   * Sets the value of the 'desc' field.
   * @param value the value to set.
   */
  public void setDesc(java.lang.String value) {
    this.desc = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.String getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.String value) {
    this.value = value;
  }

  /**
   * Creates a new InnerRecord RecordBuilder.
   * @return A new InnerRecord RecordBuilder
   */
  public static com.yshi.avro.InnerRecord.Builder newBuilder() {
    return new com.yshi.avro.InnerRecord.Builder();
  }

  /**
   * Creates a new InnerRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InnerRecord RecordBuilder
   */
  public static com.yshi.avro.InnerRecord.Builder newBuilder(com.yshi.avro.InnerRecord.Builder other) {
    return new com.yshi.avro.InnerRecord.Builder(other);
  }

  /**
   * Creates a new InnerRecord RecordBuilder by copying an existing InnerRecord instance.
   * @param other The existing instance to copy.
   * @return A new InnerRecord RecordBuilder
   */
  public static com.yshi.avro.InnerRecord.Builder newBuilder(com.yshi.avro.InnerRecord other) {
    return new com.yshi.avro.InnerRecord.Builder(other);
  }

  /**
   * RecordBuilder for InnerRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InnerRecord>
    implements org.apache.avro.data.RecordBuilder<InnerRecord> {

    private java.lang.String desc;
    private java.lang.String value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yshi.avro.InnerRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.desc)) {
        this.desc = data().deepCopy(fields()[0].schema(), other.desc);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing InnerRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yshi.avro.InnerRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.desc)) {
        this.desc = data().deepCopy(fields()[0].schema(), other.desc);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'desc' field.
      * @return The value.
      */
    public java.lang.String getDesc() {
      return desc;
    }

    /**
      * Sets the value of the 'desc' field.
      * @param value The value of 'desc'.
      * @return This builder.
      */
    public com.yshi.avro.InnerRecord.Builder setDesc(java.lang.String value) {
      validate(fields()[0], value);
      this.desc = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'desc' field has been set.
      * @return True if the 'desc' field has been set, false otherwise.
      */
    public boolean hasDesc() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'desc' field.
      * @return This builder.
      */
    public com.yshi.avro.InnerRecord.Builder clearDesc() {
      desc = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.String getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.yshi.avro.InnerRecord.Builder setValue(java.lang.String value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.yshi.avro.InnerRecord.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public InnerRecord build() {
      try {
        InnerRecord record = new InnerRecord();
        record.desc = fieldSetFlags()[0] ? this.desc : (java.lang.String) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
