/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yshi.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface NestedRecordProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"NestedRecordProtocol\",\"namespace\":\"com.yshi.avro\",\"types\":[{\"type\":\"record\",\"name\":\"InnerRecord\",\"fields\":[{\"name\":\"desc\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"value\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]},{\"type\":\"record\",\"name\":\"OuterRecord\",\"fields\":[{\"name\":\"ID\",\"type\":\"long\"},{\"name\":\"rec\",\"type\":\"InnerRecord\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends NestedRecordProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.yshi.avro.NestedRecordProtocol.PROTOCOL;
  }
}