/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yshi.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class NullableTimestamp extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4809398507065150473L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NullableTimestamp\",\"namespace\":\"com.yshi.avro\",\"fields\":[{\"name\":\"first\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NullableTimestamp> ENCODER =
      new BinaryMessageEncoder<NullableTimestamp>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NullableTimestamp> DECODER =
      new BinaryMessageDecoder<NullableTimestamp>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<NullableTimestamp> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<NullableTimestamp> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NullableTimestamp>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this NullableTimestamp to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a NullableTimestamp from a ByteBuffer. */
  public static NullableTimestamp fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public org.joda.time.DateTime first;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NullableTimestamp() {}

  /**
   * All-args constructor.
   * @param first The new value for first
   */
  public NullableTimestamp(org.joda.time.DateTime first) {
    this.first = first;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return first;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: first = (org.joda.time.DateTime)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'first' field.
   * @return The value of the 'first' field.
   */
  public org.joda.time.DateTime getFirst() {
    return first;
  }

  /**
   * Sets the value of the 'first' field.
   * @param value the value to set.
   */
  public void setFirst(org.joda.time.DateTime value) {
    this.first = value;
  }

  /**
   * Creates a new NullableTimestamp RecordBuilder.
   * @return A new NullableTimestamp RecordBuilder
   */
  public static com.yshi.avro.NullableTimestamp.Builder newBuilder() {
    return new com.yshi.avro.NullableTimestamp.Builder();
  }

  /**
   * Creates a new NullableTimestamp RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NullableTimestamp RecordBuilder
   */
  public static com.yshi.avro.NullableTimestamp.Builder newBuilder(com.yshi.avro.NullableTimestamp.Builder other) {
    return new com.yshi.avro.NullableTimestamp.Builder(other);
  }

  /**
   * Creates a new NullableTimestamp RecordBuilder by copying an existing NullableTimestamp instance.
   * @param other The existing instance to copy.
   * @return A new NullableTimestamp RecordBuilder
   */
  public static com.yshi.avro.NullableTimestamp.Builder newBuilder(com.yshi.avro.NullableTimestamp other) {
    return new com.yshi.avro.NullableTimestamp.Builder(other);
  }

  /**
   * RecordBuilder for NullableTimestamp instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NullableTimestamp>
    implements org.apache.avro.data.RecordBuilder<NullableTimestamp> {

    private org.joda.time.DateTime first;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yshi.avro.NullableTimestamp.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.first)) {
        this.first = data().deepCopy(fields()[0].schema(), other.first);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing NullableTimestamp instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yshi.avro.NullableTimestamp other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.first)) {
        this.first = data().deepCopy(fields()[0].schema(), other.first);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'first' field.
      * @return The value.
      */
    public org.joda.time.DateTime getFirst() {
      return first;
    }

    /**
      * Sets the value of the 'first' field.
      * @param value The value of 'first'.
      * @return This builder.
      */
    public com.yshi.avro.NullableTimestamp.Builder setFirst(org.joda.time.DateTime value) {
      validate(fields()[0], value);
      this.first = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'first' field has been set.
      * @return True if the 'first' field has been set, false otherwise.
      */
    public boolean hasFirst() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'first' field.
      * @return This builder.
      */
    public com.yshi.avro.NullableTimestamp.Builder clearFirst() {
      first = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NullableTimestamp build() {
      try {
        NullableTimestamp record = new NullableTimestamp();
        record.first = fieldSetFlags()[0] ? this.first : (org.joda.time.DateTime) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NullableTimestamp>
    WRITER$ = (org.apache.avro.io.DatumWriter<NullableTimestamp>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NullableTimestamp>
    READER$ = (org.apache.avro.io.DatumReader<NullableTimestamp>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
